### ISSUE TITLE
capi uint16_t vs int32_t

### ISSUE THREAD

**Issue by kdheepak** [dss-extensions/dss_capi#19]
Should [this](https://github.com/PMeira/dss_capi/blob/29b78fcb119900d743bc8e317f3070793ac821e7/include/v7/dss_capi.h#L5206) and [this](https://github.com/PMeira/dss_capi/blob/29b78fcb119900d743bc8e317f3070793ac821e7/include/v7/dss_capi.h#L4435) use `uint16_t` for the `AllocateVI` variable? `AllocateVI` is used as a boolean equivalent, correct?

The current implementation in the header file is below:

```c
DSS_CAPI_V7_DLL void Solution_BuildYMatrix(int32_t BuildOption, int32_t AllocateVI);
DSS_CAPI_V7_DLL void YMatrix_BuildYMatrixD(int32_t BuildOps, int32_t AllocateVI);
```

**Comment by PMeira** [comment]
> `AllocateVI` is used as a boolean equivalent, correct?

I kept it as `int32_t` (`LongInt` or `Integer` in Delphi mode) to maintain compatible with COM (`Solution_BuildYMatrix`) and the DDLL (`YMatrix_BuildYMatrixD`) -- there are a couple of inconsistencies like that.

https://github.com/PMeira/electricdss-src/blob/3f6f4fffe5da856bbaa001e7801ff4672124be41/Version7/Source/DDLL/DYMatrix.pas#L110-L117

https://github.com/PMeira/electricdss-src/blob/3f6f4fffe5da856bbaa001e7801ff4672124be41/Version7/Source/DLL/ImplSolution.pas#L575-L592

The `uint16_t` for booleans itself is based on the fact that COM used a 16-bit boolean. We probably can change all those in the future to simplify some things...

**Comment by PMeira** [comment]
I think we could address most of these small inconsistencies in 0.11. Since any small change will break the current API, it's better to just group them in a single release to make it easier for the downstream packages to update the code, if necessary.
