### ISSUE TITLE
Document known differences from the official OpenDSS distribution

### ISSUE THREAD

**Issue by PMeira** [dss-extensions/dss_capi#31]
There are some notable differences (such as lack of plots) and lots of tiny changes and fixes not included in the upstream version. Documenting them will help both users and developers.

**Comment by kdheepak** [comment]
We should possibly add a benchmarking suite as well? It should be nice if we could make sure we are getting the same results as the official OpenDSS distribution across a wide range of feeders and run those benchmarks on a CI as part of a nightly/weekly/monthly build.

**Comment by PMeira** [comment]
I run most of the sample systems to validate with COM in Python, I can try something in AppVeyor targetting the next release. Tracking in https://github.com/dss-extensions/dss_python/issues/9 and https://github.com/dss-extensions/dss_python/issues/10

Benchmarking will be important version 0.11, and need to be extended for other languages. I'm probably adding a comparison between the performance of the offical COM vs the dss_sharp COM too, just to be informative (I don't expect it to be better, but who knows).
