### ISSUE TITLE
dss_capi segfaults if `solve` is not called after adding PVSystem and accessing `NodeOrder`

### ISSUE THREAD

**Issue by kdheepak** [dss-extensions/dss_capi#73]
Let's say that the user has a file where they build a OpenDSS feeder (`Master.dss`). They then create a new file (`test.dss`) to load master and add `PVSystem` objects:

```
Redirect Master.dss
New PVSystem.pv_865744 bus1=b1.1.2 phases=2 kV=0.2 kVA=1.25 Pmpp=1.4 conn=wye pctPmpp=86
New PVSystem.pv_1149800 bus1=b2.1.2 phases=2 kV=0.2 kVA=1.3 Pmpp=1.4 conn=wye pctPmpp=86
New PVSystem.pv_885974 bus1=b3.1.2.3 phases=3 kV=0.48 kVA=2 Pmpp=2.5 conn=delta pctPmpp=86
New PVSystem.pv_708508 bus1=b4.1.2.3 phases=3 kV=0.48 kVA=2 Pmpp=3.2 conn=delta pctPmpp=86
```

Calling `NodeOrder` in the following code causes a segfault:

```julia
using OpenDSSDirect; const ODD = OpenDSSDirect

dss("redirect ./DSSfiles/deployment.dss")

ODD.Circuit.SetActiveElement("PVSystem.pv_708508")
ODD.CktElement.NodeOrder()
```

I believe this is because adding new a PVSystem object invalidates the `NodeRef` object. And in `./src/v7/CAPI_CktElement.pas`:

https://github.com/dss-extensions/dss_capi/blob/9503c1de34c71bf8d756e369629838fd5d0576ed/src/v7/CAPI_CktElement.pas#L1407-L1438

we access `NodeRef` without checking if it is `nil`. 

```pascal
Result[k] := GetNodeNum(NodeRef^[j]); 
```

This problem doesn't occur if the user calls `dss("solve")` before calling `ODD.CktElement.NodeOrder()`. 

I'm not sure how we want to handle this? This is not pressing since we can write this off as "user error" but ideally we should never segfault. Should we add a check in the CAPI / language bindings before accessing any global variables?

**Comment by PMeira** [comment]
> I'm not sure how we want to handle this? This is not pressing since we can write this off as "user error" but ideally we should never segfault. Should we add a check in the CAPI / language bindings before accessing any global variables?

Yeah, if it also crashes the official COM binary from EPRI (this one most likely does), it'd say it's another "user error" instance, but I've been adding error messages for most of them. I should be able add a check for it this week, as well as port some recent SVN commits.
